{
  parserClass="com.carbonblack.intellij.rpmmacro.parser.RpmMacroParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="RpmMacro"
  psiImplClassSuffix="Impl"
  psiPackage="com.carbonblack.intellij.rpmmacro.psi"
  psiImplPackage="com.carbonblack.intellij.rpmmacro.psi.impl"

  elementTypeHolderClass="com.carbonblack.intellij.rpmmacro.psi.RpmMacroTypes"
  elementTypeClass="com.carbonblack.intellij.rpmmacro.psi.RpmMacroElementType"
  tokenTypeClass="com.carbonblack.intellij.rpmmacro.psi.RpmMacroTokenType"

    tokens = [
        LBRACE            = '{'
        RBRACE            = '}'
        LPAREN            = '('
        RPAREN            = ')'
        COLON             = ':'
        PERCENT           = '%'
        QUESTION_MARK     = '?'
        BACKSLASH         = '\'
        ESCAPED_BACKSLASH = '\\'
    ]
}

rpmMacroFile ::= (COMMENT | macro)*

macro ::= MACRO_DEFINITION_START ( '{' IDENTIFIER '}' | IDENTIFIER ) macroBody {
    implements="com.carbonblack.intellij.rpmmacro.psi.RpmMacroMacroElement"
    mixin="com.carbonblack.intellij.rpmmacro.psi.RpmMacroMacroElementImpl"}

macroBody ::= anything+ !'\'

anything ::= ( '{' | '}' | '(' | ')' | ':' | '%' | '?' |
               IDENTIFIER | FLOAT_LITERAL | INTEGER_LITERAL | CODE | '\' | '\\' )
