{
  parserClass="com.carbonblack.intellij.rpmspec.parser.RpmSpecParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="RpmSpec"
  psiImplClassSuffix="Impl"
  psiPackage="com.carbonblack.intellij.rpmspec.psi"
  psiImplPackage="com.carbonblack.intellij.rpmspec.psi.impl"

  elementTypeHolderClass="com.carbonblack.intellij.rpmspec.psi.RpmSpecTypes"
  elementTypeClass="com.carbonblack.intellij.rpmspec.psi.RpmSpecElementType"
  tokenTypeClass="com.carbonblack.intellij.rpmspec.psi.RpmSpecTokenType"

  implements("preamble") = "com.carbonblack.intellij.rpmspec.psi.RpmSpecPreambleElement"
}

rpmSpecFile ::= item_*

private item_ ::= (macroDefinition|macro|preamble|changelogHeader|mainBodyItem|COMMENT|CRLF|TEXT|CODE|KEYWORD)

mainBodyItem ::= BODY_ITEM VALUE?

macro ::= MACRO_START (macro|MACRO_VALUE)+ MACRO_END?

keywordValue ::= (VALUE|macro)+

macroDefinition ::= KEYWORD MACRO_VALUE keywordValue?

preamble ::= KEY SEPARATOR keywordValue

changelogHeader ::= CHANGELOG_DATE CHANGELOG_NAME CHANGELOG_EMAIL TEXT? CHANGELOG_VERSION
